### ISSUE TITLE
Application crashs on "An unhandled error"

### ISSUE THREAD

**Issue by nonesak** [ridercz/ShirtShop#1]
Hello, the application crashs on "Unhandled exception occurred while processing the request".
The problems are on the pages, where you don't use include class for definition input properties (for example "ForgotPassword.cshtml.cs, LoginOtp.cshtml.cs, LoginRecovery.cshtml.cs ...)
When I leave input field empty, the application crashs with "ArgumentNullException: Value cannot be null. Parameter name: input"

**Comment by ridercz** [comment]
Fixed with commit [ff526773cfbed0f76c5b3fc002018aeb0ca7d139].
